### ISSUE TITLE
Tracking Issue 🎨

### ISSUE THREAD

**Issue by michalczaplinski** [c4rl0sbr4v0/wp-movies-demo#10]
This is a tracking issue for all the tasks that are related to the development of the WP Movies Demo that shows off the features of the Interactivity API

## Done
- https://github.com/c4rl0sbr4v0/wp-movies-demo/pull/9
- https://github.com/c4rl0sbr4v0/wp-movies-demo/pull/8
- https://github.com/c4rl0sbr4v0/wp-movies-demo/pull/7
- https://github.com/c4rl0sbr4v0/wp-movies-demo/pull/4
- https://github.com/c4rl0sbr4v0/wp-movies-demo/pull/3

## To Do

- [ ] Add a "Movie Search" block to show off how we can load server-rendered content dynamically.
- [ ] Look into making the page transitions when paginaging less jarring. Currently, there are no View Transitions like in https://wpmoviesdemo.wpcomstaging.com/. We could create custom directives that use the [View Transitions API](https://developer.chrome.com/docs/web-platform/view-transitions/).
- [ ] Replace all the mentions of `client-side transitions` with `client-side navigation`
- [ ] Keep the Interactivity API updated with latest changes in the https://github.com/WordPress/block-hydration-experiments.
- [ ] Host the demo on a production environment
- [ ] Move the repository to WordPress organization.
